/**
 * shared/i18n.ts — 中英双语
 *
 * 两层机制：
 * 1) 界面固定文案：内置词典（以中文原文为 key），切换即时、零网络
 * 2) ezPLM 动态内容（器件描述/分类/参数名等中文数据）：英文模式下经 Gemini
 *    批量翻译（300ms 合批 + 会话/localStorage 双缓存，同一文案只翻一次）
 */
import { create } from 'zustand';
import { useEffect, useState } from 'react';
import { geminiComplete, extractJson, geminiAvailable } from '../providers/gemini';

export type Lang = 'zh' | 'en';

interface LangState {
  lang: Lang;
  toggle: () => void;
  setLang: (l: Lang) => void;
}

export const useLangStore = create<LangState>((set) => ({
  lang: (localStorage.getItem('cc_lang') as Lang) || 'zh',
  toggle: () => set((s) => {
    const lang: Lang = s.lang === 'zh' ? 'en' : 'zh';
    localStorage.setItem('cc_lang', lang);
    return { lang };
  }),
  setLang: (lang) => { localStorage.setItem('cc_lang', lang); set({ lang }); },
}));

/* ───────────── 固定文案词典（key = 中文原文） ───────────── */
const DICT: Record<string, string> = {
  // 品牌
  '硬件原型工坊': 'Tindie Proto',
  'AI 方案生成、器件选型与 PCB 预布局': 'AI Hardware Planning, Parts Selection & PCB Pre-Layout',
  // 顶栏
  '导出PCB': 'Export PCB', '方案报告': 'Report', '导出设计': 'Export', '导入设计': 'Import',
  // 左栏
  'AI 生成方案': 'AI Design Generator',
  '如：USB转串口调试器 / WiFi物联网节点 / 12V车载CAN控制器': 'e.g. USB-UART debugger / WiFi IoT node / 12V automotive CAN controller',
  '生成方案上画布': 'Generate & Place', '生成中…': 'Generating…',
  '型号搜索': 'Part Search', '封装库': 'Footprints', '定制模块': 'Custom Parts',
  '已连接 ezPLM 元器件库（实时检索）': 'ezPLM parts library connected (live)',
  'ezPLM 库连接失败，使用演示目录': 'ezPLM unavailable, using demo catalog',
  '微控制器': 'MCU', '电源管理': 'Power', '无源器件': 'Passive', '连接器': 'Connector', '集成电路': 'IC',
  '机电（继电器/开关）': 'Electromech (Relay/Switch)', '传感器': 'Sensor', '射频': 'RF', '电源': 'Power', '无源': 'Passive',
  '仅显示本组织物料': 'My organization only',
  '搜索型号、封装、关键词...': 'Search MPN, footprint, keyword...',
  '找到': 'Found', '个结果': 'results',
  '＋ 新建定制器件（AI 提取 / 手工向导）': '＋ New Custom Part (AI extract / manual)',
  '还没有定制器件': 'No custom parts yet', '上传 Datasheet 或手工填写管脚即可构建': 'Upload a datasheet or fill in pins to build one',
  '自建': 'Custom',
  // 画布工具栏
  '撤销': 'Undo', '重做': 'Redo', '清除': 'Clear', '2D 布局': '2D Layout', '3D 视图': '3D View',
  'Top层': 'Top', 'Bottom层': 'Bottom', '位号': 'RefDes',
  'R 旋转 · L 换层 · Delete 删除 · 拖位号可移动': 'R rotate · L flip · Delete remove · drag refdes to move',
  '从左侧添加器件，自动按电气规则摆放': 'Add parts from the left — auto-placed by electrical rules',
  '旋转': 'Rotate', '隐位号': 'Hide Ref', '移除': 'Remove',
  // 底栏
  '定位孔': 'Mounting Holes', '切角': 'Cutout', '圆角': 'Radius',
  'BOM清单': 'BOM', '系统框图': 'Block Diagram', '原理图': 'Schematic',
  // 右栏
  '当前元件': 'Component', 'AI顾问': 'AI Advisor',
  '点击画布中的元件查看详情': 'Select a component on the canvas to see details',
  '官网检索': 'Vendor Site', '官网': 'Vendor', 'PDF检索': 'Find PDF', 'PDF下载': 'Datasheet', '无PDF': 'No PDF',
  '分类：': 'Category: ',
  '核心参数': 'Key Specs',
  'PCB 设计库文件': 'PCB Library Files', '原理图符号': 'Schematic Symbol', 'PCB 封装': 'PCB Footprint', '3D 模型': '3D Model',
  'ezPLM 精确数据 ✓': 'ezPLM exact data ✓',
  '拉取库文件中…（暂用名字解析）': 'Fetching library file… (name-parsed for now)',
  '文件解析失败 · 用名字解析兜底': 'File parse failed · fallback to name parsing',
  '接口未提供文件链接 · 名字解析': 'No file link from API · name-parsed',
  'STEP 源文件（ezPLM）': 'STEP source (ezPLM)', 'ezPLM 未提供该器件的 STEP 文件': 'No STEP file from ezPLM',
  'ezPLM 真实 STEP 模型 ✓': 'Real STEP model (ezPLM) ✓',
  'STEP 转换中…（首次需下载 3D 引擎）· 暂为参数化': 'Converting STEP… (3D engine downloads once) · parametric for now',
  'STEP 转换失败 · 参数化预览': 'STEP conversion failed · parametric preview',
  '准备转换 STEP…': 'Preparing STEP conversion…', '参数化 3D 预览': 'Parametric 3D preview',
  '拖拽旋转 · 滚轮缩放 · 双击复位': 'Drag to rotate · scroll to zoom · double-click to reset',
  '采购渠道': 'Suppliers', '实时': 'Live', '演示': 'Demo', '库存': 'Stock', '跳转 ↗': 'Open ↗',
  '未收录该型号': 'not listed', '查询中… / 未配置': 'querying… / not configured',
  '替代料（AI × ezPLM）': 'Alternatives (AI × ezPLM)', 'AI 搜索替代料': 'AI Find Alternatives', '搜索中…': 'Searching…',
  '参考设计（来自 ezPLM）': 'Reference Designs (ezPLM)',
  '封装占位器件 · 补充信息': 'Placeholder Part · Complete Info',
  '输入器件型号，如 GD32F103C8T6': 'Enter MPN, e.g. GD32F103C8T6', '设为型号': 'Set MPN',
  '从 ezPLM 库关联': 'Link from ezPLM', '匹配型号': 'Full Match', '仅符号': 'Symbol Only', '仅封装': 'Footprint Only',
  '从 URL / PDF 提取生成': 'Extract from URL / PDF', '上传符号 (SVG)': 'Upload Symbol (SVG)',
  // BOM
  'BOM 总价（DigiKey 实时价优先）': 'BOM Total (DigiKey live prices first)', '导出 CSV': 'Export CSV', '全屏': 'Fullscreen',
  '序号': '#', '厂商': 'Mfr', '封装': 'Footprint', '来源': 'Source', '单价': 'Unit Price', '数量': 'Qty', '型号': 'MPN',
  // 弹窗
  'AI 方案建议 · 请确认': 'AI Proposal · Confirm', '✓ Gemini 生成': '✓ Generated by Gemini', '演示引擎': 'Demo engine',
  '仅加载核心器件': 'Core parts only', '取消': 'Cancel', '确认上画布': 'Place on Canvas', '个器件': 'parts',
  '关联库器件': 'Link Library Part', '创建': 'Create',
  // 向导
  '定制器件构建向导': 'Custom Part Wizard',
  '保存到定制库': 'Save to Library', '添加管脚': 'Add Pin', '管脚定义': 'Pin Definition',
  '封装参数': 'Package', '封装预览': 'Footprint Preview', '焊盘': 'pads', '模块轮廓（可选）': 'Module Outline (optional)',
};

/** 固定文案翻译：zh 模式原样返回；en 模式查词典，未命中返回原文 */
export function useT() {
  const lang = useLangStore((s) => s.lang);
  return (text: string): string => (lang === 'en' ? DICT[text] ?? text : text);
}

/* ───────────── 动态内容翻译（ezPLM 中文数据 → 英文） ───────────── */
const trCache = new Map<string, string>();
try {
  const saved = JSON.parse(localStorage.getItem('cc_tr_cache') ?? '{}') as Record<string, string>;
  for (const [k, v] of Object.entries(saved)) trCache.set(k, v);
} catch { /* 忽略损坏缓存 */ }

let pendingQueue = new Set<string>();
let flushTimer: ReturnType<typeof setTimeout> | null = null;
const listeners = new Set<() => void>();

function persistCache() {
  const obj: Record<string, string> = {};
  let n = 0;
  for (const [k, v] of trCache) { obj[k] = v; if (++n >= 800) break; }
  localStorage.setItem('cc_tr_cache', JSON.stringify(obj));
}

async function flushQueue() {
  const batch = [...pendingQueue].slice(0, 40);
  pendingQueue = new Set([...pendingQueue].slice(40));
  if (!batch.length) return;
  try {
    if (!(await geminiAvailable())) return;
    const text = await geminiComplete(
      `将以下电子元器件领域的中文文本翻译成简洁的英文（专业术语标准化，如"运算放大器"→"op-amp"）。严格输出 JSON 字符串数组，与输入等长、顺序一致，勿输出其它文字：\n${JSON.stringify(batch)}`,
    );
    const out = extractJson<string[]>(text);
    batch.forEach((src, i) => { if (typeof out[i] === 'string' && out[i]) trCache.set(src, out[i]); });
    persistCache();
    listeners.forEach((fn) => fn());
  } catch { /* 翻译失败保留原文，下次进入视图重试 */ }
  if (pendingQueue.size) { flushTimer = setTimeout(flushQueue, 400); } else { flushTimer = null; }
}

const hasCJK = (s: string) => /[\u4e00-\u9fff]/.test(s);

/** 动态文本翻译 hook：en 模式下含中文的文本进入批量翻译队列，完成后自动刷新 */
export function useTranslated(text: string | undefined): string | undefined {
  const lang = useLangStore((s) => s.lang);
  const [, force] = useState(0);
  useEffect(() => {
    if (lang !== 'en' || !text || !hasCJK(text) || trCache.has(text)) return;
    pendingQueue.add(text);
    if (!flushTimer) flushTimer = setTimeout(flushQueue, 300);
    const cb = () => force((x) => x + 1);
    listeners.add(cb);
    return () => { listeners.delete(cb); };
  }, [lang, text]);
  if (lang !== 'en' || !text) return text;
  return trCache.get(text) ?? text;
}
